spring:
  datasource:
    url: jdbc:h2:mem:test_task
    username: root
    password: root!Q1q
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000